/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: "jit",
  content: ["**/**.html.twig"],
  safelist: [
    "flex",
    "rotate-45",
    "translate-y-3.5",
    "absolute",
    "duration-300",
    "ease-out",
    "bg-nav-btn",
    "opacity-0",
    "-rotate-45",
    "-translate-y-3.5",
    "top-28",
    "duration-300",
    "ease-out",
    "top-up",
    "duration-300",
    "ease",
    "bg-green-400",
    "top-1/2",
    "translate-x-full",
    "bg-orange-400",
    "hover:bg-orange-600",
    "w-open-nav",
    "rotate-180",
    "w-closed-nav",
    "w-content-space-open",
    "w-content-space-closed",
    "mx-auto",
    "bg-nav-btn",
    "text-gray-500",
    "gap-x-10",
    "gap-y-5",
    "shadow-form",
    "h-10",
    "flex-wrap",
    "w-modal-width",
    "max-h-modal-height",
    "gap-2",
  ],
  theme: {
    extend: {
      colors: {
        "regal-blue": "#243c5a",
        "the-grey": "#b7bbc8",
        "the-grey-2": "#d4d4d4",
        "light-dark": "#353535",
        "devis-bg": "#adadad",
        "landing-bg": "#FDB833",
        "button-blue": "#0252C5",
        "button-blue-hover": "#023c8d",
        "nav-bg": "#FBFCFC",
        "nav-menu": "#000D31",
        "nav-btn": "#3347FD",
        "card-grey": "#8A92A6",
        "progress-bar-1": "#3A57E8",
        "progress-bar-2": "#08B1BA",
      },
      spacing: {
        "90-vh": "90vh",
        "80-vh": "80vh",
        "95%": "95%",
        "2px": "2px",
        "15%": "15%",
        A4w: "794px",
        A4h: "1123px",
        "5px": "5px",
        "15px": "15px",
        "35%": "35%",
        "50px": "50px",
        "70%": "70%",
        "closed-nav": "48px",
        "open-nav": "257px",
        "modal-width": "1031px",
        "modal-height": "90%",
        up: "-1000px",
      },
      width: {
        "content-space-open": "calc(100% - 257px)",
        "content-space-closed": "calc(100% - 48px)",
        "grid-dashboard-space": "calc(100% - 410px)",
      },
      borderRadius: {
        "10px": "10px",
      },
      fontSize: {
        "15px": "15px",
      },
      fontFamily: {
        roboto: ["Roboto", "sans-serif"],
      },
      minHeight: {
        "90vh": "90vh",
        "80vh": "80vh",
      },
      boxShadow: {
        form: "0px 4px 18px 0px rgba(158, 168, 189, 0.31)",
      },
    },
  },
  plugins: [],
};
