/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./assets//*.js", "./templates//*.html.twig"],
  safelist: [
      "btn",
    "bg-green-400",
    "top-1/2",
    "translate-x-full",
    'bg-orange-400',
    'hover:bg-orange-600',
    "flex",
    "justify-between",
    "w-full",
    "items-center",
    "py-3",
    "px-5",
    "h-14",
    "bg-[#353535]",
    "material-symbols-outlined",
    "transition-all",
    "duration-300",
    "text-white",
    "cursor-pointer",
    "hover:text-red-500",
    "bg-white",
    "py-2",
    "px-4",
    "rounded-md",
    "text-base",
    "font-bold",
    "hover:bg-lime-500",
    "Generator",
    "font-roboto",
    "w-A4w",
    "h-A4h",
    "bg-white",
    "my-5",
    "mx-auto",
    "p-5",
    "border",
    "border-solid",
    "border-gray-300",
      "Grid",
      "table",
      "th",
      "td",
      "remove_button",
    "shadow-md",
    "top",
    "h-auto",
    "justify-start",
    "items-start",
    "society",
    "w-1/2",
    "logoName",
    "w-36",
    "h-36",
    "society-info",
    "mt-15px",
    "p-5px",
    "text-lg",
    "mb-3",
    "font-semibold",
    "text-15px",
    "top-r",
    "devis",
    "bg-the-grey-2",
    "p-15px",
    "rounded-10px",
    "text-2xl",
    "devis-info",
    "leading-none",
    "my-1",
    "client",
    "mt-3",
    "client-info",
    "table-container",
    "objet",
    "self-center",
    "mb-5",
    "ml-5px",
    "commande-title",
    "ml-1",
    "wrapper",
    "h-56",
    "mid",
    "condition",
    "mt-12",
    "w-70%",
    "total",
    "w-35%",
    "mr-5px",
    "total-sub-container",
    "m-0",
    "text-base",
    "total-tab",
    "ml-5px",
    "p-4",
    "w-40",
    "bg-light-dark",
    "text-lg",
    "text-right",
    "text-white",
    "signature",
    "mr-5px",
    "ml-auto",
    "pt-3",
    "pl-3",
    "w-52",
    "h-28",
    "bottom",
    "divider",
    "w-full",
    "h-2px",
    "rounded-2xl",
    "my-5",
    "bottom-info",
    "text-sm"
  ],

  theme: {
    extend: {
      colors: {
        "regal-blue": "#243c5a",
        "the-grey": "#b7bbc8",
        "the-grey-2": "#d4d4d4",
        "light-dark": "#353535",
        "devis-bg": "#adadad",
        "landing-bg": "#FDB833",
        "button-blue": "#0252C5",
        "button-blue-hover": "#023c8d",
      },
      spacing: {
        "90-vh": "90vh",
        "95%": "95%",
        "2px": "2px",
        "15%": "15%",
        A4w: "794px",
        A4h: "1123px",
        "5px": "5px",
        "15px": "15px",
        "35%": "35%",
        "50px": "50px",
        "70%": "70%",
      },
      borderRadius: {
        "10px": "10px",
      },
      fontSize: {
        "15px": "15px",
      },
      fontFamily: {
        roboto: ["Roboto", "sans-serif"],
      },
      minHeight: {
        "90vh": "90vh",
      },
    },
  },
  plugins: [],
};
